# .travis.yml

language: node_js
node_js:
  - 8.11.2
dist: trusty
sudo: required

branches:
  except:
    - gh-pages # don't try to build the deploy branch

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless
  - ng build --prod

after_success:
  - npm run coveralls

deploy:
  provider: firebase
  skip-cleanup: true
  token: $FIREBASE_TOKEN
  on:
    branch: master
  local_dir: dist
