# .travis.yml

language: node_js
node_js:
  - 6.11.0
dist: trusty
sudo: required

cache:
  directories:
    - node_modules

addons:
  chrome: stable

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: unit tests
      script: npm test -- --single-run
    - stage: build
      script: npm run build
    - stage: e2e tests
      script: xvfb-run npm run e2e
