# .travis.yml

language: node_js
node_js:
  - 6.11.0
dist: trusty
sudo: required

branches:
  except:
    - gh-pages # don't try to build the deploy branch

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - npm run lint
  - npm run test:headless -- --single-run
  - xvfb-run npm run e2e
  - npm run build -- --base-href "https://cse403trackforever.github.io/webapp/" # TODO use --prod when ready

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: dist
